import {createSlice} from '@reduxjs/toolkit';

// set up our initial state (HAS to be an object, even if it's a single property)
// similar to setting up a UseState 
//this is the state that will be accessed globally throughout our app 
const initialState= {
    value: 0,
    numbers: []
}


//export is used to make it global
//HAVE to give the slice a unique name, initial state, and the reducer functions 
//after providing all of this, redux-toolkit sets everything up for you 
export const counterSlice= createSlice({
    name: "counter",
    initialState, // this is referencing the above initial state 
    //reducers are functions designed to modify global state 
    //state parameter -access the current state 
    reducers: {
        increment: (state)=> {
 //modify state directly, changes are availble in any component in app
            state.value+=1 
        }, 
        decrement: (state)=>{
            state.value -=1; 
        },
        incrementByAmount: (state,action)=>{
    // the action consists of a type and a payload
    // the type specifies the reducer function we are calling
    // the payload is the argument that gets passed in to the action
        state.value
 // increment my current state value by the parameter we get from the action
        state.value+=action.payload
        //payload an be anything 
        },
        //state is what already exists, action is what will happen 
        addNumber: (state,action) => {
            console.log("add number")
            console.log(action.payload)
            state.numbers.push(action.payload)
            // otherway would be 
            //state.numbers=[...state.numbers, action.payload]
        },
        removeNumber: (state) =>{
            state.numbers.pop()
        }
    }
})

//the increment below is the action 
//generated by createSlice, they correspond w above reducer functions
//when an action is dispatched they will trigger said reducer function 
export const {increment, decrement, incrementByAmount, addNumber, removeNumber }= counterSlice.actions;

export default counterSlice.reducer


//clientstate- better for Redux 
//server state- better for APIs